"""create minimal groupware schema

Revision ID: 8f624aab11bf
Revises:
Create Date: 2026-08-21 13:53:41.053895
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8f624aab11bf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_policies",
        sa.Column("record_id", sa.String(length=96), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "TRAVEL",
                "EXPENSE",
                "LEAVE",
                "APPROVAL",
                "SECURITY",
                name="policytype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "ACTIVE", "ARCHIVED", name="policystatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("record_id"),
        sa.UniqueConstraint("policy_id", "version", name="uq_policy_version"),
    )
    op.create_index(
        op.f("ix_company_policies_policy_id"), "company_policies", ["policy_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_policies_status"), "company_policies", ["status"], unique=False
    )
    op.create_index(op.f("ix_company_policies_type"), "company_policies", ["type"], unique=False)
    op.create_table(
        "departments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("parent_department_id", sa.String(length=64), nullable=True),
        sa.Column("manager_employee_id", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("department_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.String(length=120), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "EMPLOYEE",
                "MANAGER",
                "POLICY_OWNER",
                name="employeerole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("manager_id", sa.String(length=64), nullable=True),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("leave_balance", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_email"), "employees", ["email"], unique=True)
    op.create_table(
        "policy_sections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("policy_record_id", sa.String(length=96), nullable=False),
        sa.Column("section_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_record_id"], ["company_policies.record_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_record_id", "section_id", name="uq_policy_section_id"),
    )
    op.create_index(
        op.f("ix_policy_sections_policy_record_id"),
        "policy_sections",
        ["policy_record_id"],
        unique=False,
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "GENERAL",
                "BUSINESS_TRIP",
                "EXPENSE",
                "LEAVE",
                name="approvaltype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="approvalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("attachment_metadata", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_author_id"), "approvals", ["author_id"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    op.create_table(
        "credentials",
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("employee_id"),
    )
    op.create_table(
        "approval_lines",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("approval_id", sa.String(length=64), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("approver_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING",
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="approvallinestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("acted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["approval_id"], ["approvals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("approval_id", "round", "step", name="uq_approval_line_round_step"),
    )
    op.create_index(
        op.f("ix_approval_lines_approval_id"), "approval_lines", ["approval_id"], unique=False
    )
    op.create_index(
        op.f("ix_approval_lines_approver_id"), "approval_lines", ["approver_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approval_lines_approver_id"), table_name="approval_lines")
    op.drop_index(op.f("ix_approval_lines_approval_id"), table_name="approval_lines")
    op.drop_table("approval_lines")
    op.drop_table("credentials")
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_author_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_policy_sections_policy_record_id"), table_name="policy_sections")
    op.drop_table("policy_sections")
    op.drop_index(op.f("ix_employees_email"), table_name="employees")
    op.drop_table("employees")
    op.drop_table("departments")
    op.drop_index(op.f("ix_company_policies_type"), table_name="company_policies")
    op.drop_index(op.f("ix_company_policies_status"), table_name="company_policies")
    op.drop_index(op.f("ix_company_policies_policy_id"), table_name="company_policies")
    op.drop_table("company_policies")
    # ### end Alembic commands ###
